### ISSUE TITLE
Agent fails to stage

### ISSUE THREAD

**Issue by egypt** [FactionC2/Faction#24]
**Describe the bug**
Agents fail to stage.

** Error Message **

IPs redacted. 
* Victim: 10.1.1.1
* TransportHTTP server: 10.2.2.2
* Faction: 10.3.3.3

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]·········································································································································
      Request starting HTTP/1.1 POST https://10.2.2.2/weather.html application/json 2········
(06/10/2019 21:06:13)[INFO] Staging URL: https://10.3.3.3/api/v1/staging/I6RC_CuRQyk/x6-cy-1N/···························································································
(06/10/2019 21:06:13)[INFO] Key Name: p1BaXSwTuMW-S-0y·········································································································································
(06/10/2019 21:06:13)[INFO] Secret: TpDRMtVZcPdvsyMRzErJGXA8HcBkMRPtZkAtQqvgEpLoGReWLy8jJlv6ZY7ZQJTB···························································································
(06/10/2019 21:06:13)[INFO] Sending Staging Message: {"TransportId": 3,"Message": "eyJQYXlsb2FkTmFtZSI6Ikk2UkNfQ3VSUXlrIiwiSVYiOiIyZldrYWVuU2VSZGQvZEZIS082T29RPT0iLCJNZXNzYWdlIjoiK3F1L0pLZkFZ
NzVhUHhGTkNaN3pvbFhidUo4Y1JyNzhKa05QSnVXcVVZVGRwR2dENXdVRUZzMENZMUx3QU1DbnJIMktLcnR4VGx1WkNrdlZiU3hISXB2bWd5WXFILzliQktJOUUwZkxqMHBYWTI2Uk1GZVN1SVBXTWEwN2ZBRVBER3QxYm5jT1NKR3ZxT2VOd1laUi92c0V
iR2szODV5Z2JLR3d5Ykx2RkF6ZTk1TTN1T25vUVpIUlVLYWpkd0NLcEJMK1J5T2czVlplSEJ3ZXZQTlI3alk5WkxCZkJoZzZkanV6Q0pjTWRwWk0zbERJMWI4ZmJVODN4Vzd0WFNzZCIsIkhNQUMiOiI0eXk2YlJMTGFCQS90OFZnV3RyUUZWc3kwTmFGdG
dQWS94SmRNeEFSSjVNPSJ9", "SourceIp":"10.1.1.1"}·································
(06/10/2019 21:06:24)[INFO] Got Response: "ERROR"·····································································
·················································································································
fail: Microsoft.AspNetCore.Server.Kestrel[13]··················································································
      Connection id "0HLNDSSH95ILB", Request id "0HLNDSSH95ILB:0000000A": An unhandled exception was thrown by the application.····
System.Collections.Generic.KeyNotFoundException: The given key 'AgentName' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)······················
   at httpserver.HttpProfile.HandlePost(HttpContext httpContext, Dictionary`2 Message)································
   at httpserver.Services.EndpointHandler.Handle(HttpContext httpContext) in /app/Services/EndpointHandler.cs:line 107
   at httpserver.Startup.<>c__DisplayClass1_0.<Configure>b__1(HttpContext httpContext) in /app/Startup.cs:line 77
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)················································
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)····················
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]·········································································································································
      Request finished in 10434.9228ms 500·····················································································································································
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]·········································································································································
      Request starting HTTP/1.1 POST https://10.2.2.2/weather.html application/json 2
(06/10/2019 21:06:29)[INFO] Staging URL: https://10.3.3.3/api/v1/staging/I6RC_CuRQyk/x6-cy-1N/
(06/10/2019 21:06:29)[INFO] Key Name: p1BaXSwTuMW-S-0y································
(06/10/2019 21:06:29)[INFO] Secret: TpDRMtVZcPdvsyMRzErJGXA8HcBkMRPtZkAtQqvgEpLoGReWLy8jJlv6ZY7ZQJTB
(06/10/2019 21:06:29)[INFO] Sending Staging Message: {"TransportId": 3,"Message": "eyJQYXlsb2FkTmFtZSI6Ikk2UkNfQ3VSUXlrIiwiSVYiOiJOSUJiN0lTRGNGZzF2RTJsYWE0bC9BPT0iLCJNZXNzYWdlIjoid2hSQ1RRS2FP
RVJIUE5GanNrYkpibmpkSU41WGJLRVVDenRDWHZMbVV4aGkyUEV1Z2htalBOU0ZMbFJFM1hqbGpzdHI0ZmNqaFNtNTJha2pocWt3QnpISjdGWFZFSXVnL3Uxd3d2MXVoV2NjWmU2Y3ZRQVNYSTNLV2UrUi9uU1gzWE5GczRWSDhGTVlPV1FDVStDY3lsTkR
VS0ZBenE3OENramlCbEF6cU9td3M3U1FtWEIwZUgxeWswRnhhR0J1cU03eEFrSGhueW1YV3pTa3IraTJDak9ZOC8xdEJnVVlYbWtaQlVDMFNpdGRxWk9EbXhrTHNkLzFDN0E2cHdxWCIsIkhNQUMiOiIyeFpjMXUybkNvaDd4dDI3Z01CbkZoem9neTR1dS
9mb0pVNllkTlNzb2pJPSJ9", "SourceIp":"10.1.1.1"}························································
(06/10/2019 21:06:39)[INFO] Got Response: "ERROR"·········································
······················································································
fail: Microsoft.AspNetCore.Server.Kestrel[13]·········································································
      Connection id "0HLNDSSH95ILB", Request id "0HLNDSSH95ILB:0000000B": An unhandled exception was thrown by the application.
System.Collections.Generic.KeyNotFoundException: The given key 'AgentName' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)···································································
   at httpserver.HttpProfile.HandlePost(HttpContext httpContext, Dictionary`2 Message)
   at httpserver.Services.EndpointHandler.Handle(HttpContext httpContext) in /app/Services/EndpointHandler.cs:line 107
   at httpserver.Startup.<>c__DisplayClass1_0.<Configure>b__1(HttpContext httpContext) in /app/Startup.cs:line 77
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)····································································
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 10520.1177ms 500

```

**To Reproduce**
1. make a transport
2. download payload
3. run on victim
4. see error messages in TransportHTTP service

**Expected behavior**
Agent stages and becomes useful.

**Desktop (please complete the following information):**
 - OS: Debian 9

**Additional context**
The first time I ran the payload it staged fine. I ran `help` and it worked as expected. Then `show commands` in the console and nothing came back. Re-ran payload and saw a bunch of the above errors.

**Comment by jaredhaight** [comment]
Adding some logs from @egypt. Looks like Core is trying to process the staging request as an agent checkin, so something between API and Core is getting confused. At the very least need to re-enable the try/catch around message processing in Core so that it doesn't completely crap the bed if it throws an error.

*API Log*
```
api_1           | (06/10 21:54:35)[User Role - Authorized Groups] - group id: 2
api_1           | (06/10 21:54:35)[User Role - Authorized Groups] - checking group: Operator
api_1           | (06/10 21:54:35)[get_role_id] - Getting role Operator
api_1           | (06/10 21:54:35)[get_role_id] - Got role 3
api_1           | (06/10 21:54:35)[User Role - Authorized Groups] - group id: 3
api_1           | (06/10 21:54:35)[User Role - Authorized Groups] - checking group: system
api_1           | (06/10 21:54:35)[get_role_id] - Getting role system
api_1           | (06/10 21:54:35)[get_role_id] - Got role 1
api_1           | (06/10 21:54:35)[User Role - Authorized Groups] - group id: 1
api_1           | (06/10 21:54:35)[User Role - Authorized Groups] - Authorized.
api_1           | (06/10 21:54:35)[staging_message:new_staging_message] - Got staging request. PayloadName: LMiT4sDc_qk ID: sChWjsx-
api_1           | (06/10 21:54:35)[staging_message:new_staging_message] - Publishing: {'PayloadName': 'LMiT4sDc_qk', 'IV': 'i9l6ClD0hz2QGzZBvqe4xQ==', 'Message': 'A7vs027aILOPjyGzQdLcJCivEm55
OQ79RwZDBwMbIFB2kLR8iSfhQBhUWSFxnMwlwmPU2/dOQRqNoP/IMXKy8tOSpfit8xHqfNY6up5J5DTUj2rPK/NTr7DJylTv+mYfKs30AtSPLEQsfEwy17/iFyBKCfE4B5POqyegr2q9cfDQe2NZE0KgMT/Xtx1NJPEX89PcIlC3ojELgZpvCZKYeevKFZoKNNddLBVCm8hElmrNlaf7lP0EcC4yKmEkfUGd', 'HMAC': 'nFzgkRdrHpoDXZHSlAN911U+UAapXRJECfCawVl5syo=', 'TransportId': '3', 'SourceIp': '10.1.1.1'}
api_1           | (06/10 21:54:35)[rabbitmq-producer:send_request] - Got message: {'PayloadName': 'LMiT4sDc_qk', 'IV': 'i9l6ClD0hz2QGzZBvqe4xQ==', 'Message': 'A7vs027aILOPjyGzQdLcJCivEm55OQ79RwZDBwMbIFB2kLR8iSfhQBhUWSFxnMwlwmPU2/dOQRqNoP/IMXKy8tOSpfit8xHqfNY6up5J5DTUj2rPK/NTr7DJylTv+mYfKs30AtSPLEQsfEwy17/iFyBKCfE4B5POqyegr2q9cfDQe2NZE0KgMT/Xtx1NJPEX89PcIlC3ojELgZpvCZKYeevKFZoKNNddLBVCm8hElmrNlaf7lP0EcC4yKmEkfUGd', 'HMAC': 'nFzgkRdrHpoDXZHSlAN911U+UAapXRJECfCawVl5syo=', 'TransportId': '3', 'SourceIp': '10.1.1.1'} with routing_key: NewStagingMessage
api_1           | (06/10 21:54:35)[rabbitmq-consumer:update_queue] - Adding message id: 19dd5620-ea22-4160-90ac-a4d2cc6c4b58
api_1           | (06/10 21:54:35)[rabbitmq-producer:send_request] - Publishing message..
api_1           | (06/10 21:54:35)[rabbitmq-producer:send_request] - Got correlation_id: 19dd5620-ea22-4160-90ac-a4d2cc6c4b58
api_1           | (06/10 21:54:35)[staging_message:new_staging_message] - Waiting for 10 seconds
api_1           | (06/10 21:54:35)[staging_message:new_staging_message] - Waiting for 10 seconds
api_1           | (06/10 21:54:36)[staging_message:new_staging_message] - Waiting for 9 seconds
api_1           | (06/10 21:54:37)[staging_message:new_staging_message] - Waiting for 8 seconds
api_1           | (06/10 21:54:38)[staging_message:new_staging_message] - Waiting for 7 seconds
api_1           | (06/10 21:54:39)[staging_message:new_staging_message] - Waiting for 6 seconds
api_1           | (06/10 21:54:40)[staging_message:new_staging_message] - Waiting for 5 seconds
api_1           | (06/10 21:54:41)[staging_message:new_staging_message] - Waiting for 4 seconds
api_1           | (06/10 21:54:42)[staging_message:new_staging_message] - Waiting for 3 seconds
api_1           | (06/10 21:54:43)[staging_message:new_staging_message] - Waiting for 2 seconds
api_1           | (06/10 21:54:44)[staging_message:new_staging_message] - Waiting for 1 seconds
api_1           | (06/10 21:54:45)[staging_message] - Timed out.
api_1           | (06/10 21:54:45)[user model] - save session called
api_1           | (06/10 21:54:52)[User Role - Authorized Groups] - Checking if authenticated..
api_1           | Trying API key lookup 
api_1           | Got API KEY: p1BaXSwTuMW-S-0y 
api_1           | Returning User with Id: 1
api_1           | (06/10 21:54:52)[user model] - User loaded from request 
api_1           | (06/10 21:54:52)[User Role - Authorized Groups] - checking group: Admin
api_1           | (06/10 21:54:52)[get_role_id] - Getting role Admin
api_1           | (06/10 21:54:52)[get_role_id] - Got role 2
api_1           | (06/10 21:54:52)[User Role - Authorized Groups] - group id: 2
api_1           | (06/10 21:54:52)[User Role - Authorized Groups] - checking group: Operator
api_1           | (06/10 21:54:52)[get_role_id] - Getting role Operator
api_1           | (06/10 21:54:52)[get_role_id] - Got role 3
api_1           | (06/10 21:54:52)[User Role - Authorized Groups] - group id: 3
```

*Core Log*
```
core_1          | info: Faction.Common.Backend.EventBus.RabbitMQ.EventBusRabbitMQ[0]
core_1          |       Sending message to Exchange: Core with RoutingKey: ConsoleMessageAnnouncement
core_1          |
core_1          | Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
core_1          |    at Faction.Core.Handlers.NewAgentCheckinEventHandler.Handle(NewAgentCheckin agentCheckinMsg, String replyTo, String correlationId) in /app/Handlers/NewAgentCheckinEventHandler.cs:line 93
core_1          |    at Faction.Common.Backend.EventBus.RabbitMQ.EventBusRabbitMQ.ProcessEvent(String eventName, String message, String replyTo, String correlationId) in /home/jared/source/faction/Faction.Common/Backend/EventBusRabbitMQ/EventBusRabbitMQ.cs:line 328
core_1          |    at Faction.Common.Backend.EventBus.RabbitMQ.EventBusRabbitMQ.<>c__DisplayClass22_0.<<CreateConsumerChannel>b__0>d.MoveNext() in /home/jared/source/faction/Faction.Common/Backend/EventBusRabbitMQ/EventBusRabbitMQ.cs:line 266
core_1          | --- End of stack trace from previous location where exception was thrown ---
core_1          |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
core_1          | --- End of stack trace from previous location where exception was thrown ---
core_1          |    at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by jaredhaight** [comment]
I *believe* this has been solved with the recent re-write of the HTTP Transport. I haven't had any issues in my testing. Going to go ahead and close this issue, feel free to reopen it if you run into any more trouble.
