### ISSUE TITLE
Core crashes on invalid command

### ISSUE THREAD

**Issue by jaredhaight** [FactionC2/Faction#30]
**Describe the bug**
When you enter a command that Core doesn't know, it crashes. It shouldn't do that.

**Error Message**
Please copy and paste any error messages here.

```
core_1          | fail: Microsoft.EntityFrameworkCore.Query[10100]
core_1          |       An exception occurred while iterating over the results of a query for context type 'Faction.Common.Backend.Database.FactionDbContext'.
core_1          |       System.InvalidOperationException: Sequence contains no elements
core_1          |          at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
core_1          |          at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
core_1          |          at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
core_1          |          at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
core_1          | System.InvalidOperationException: Sequence contains no elements
core_1          |    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
core_1          |    at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
core_1          |    at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
core_1          |    at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
core_1          | fail: Microsoft.EntityFrameworkCore.Query[10100]
core_1          |       An exception occurred while iterating over the results of a query for context type 'Faction.Common.Backend.Database.FactionDbContext'.
core_1          |       System.InvalidOperationException: Sequence contains no elements
core_1          |          at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
core_1          |          at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
core_1          |          at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
core_1          |          at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
core_1          |          at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
core_1          |          at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
core_1          |          at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
core_1          | System.InvalidOperationException: Sequence contains no elements
core_1          |    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
core_1          |    at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
core_1          |    at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
core_1          |    at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
core_1          |    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
core_1          |    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
core_1          |    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
core_1          |
core_1          | Unhandled Exception: System.InvalidOperationException: Sequence contains no elements
core_1          |    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
core_1          |    at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
core_1          |    at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
core_1          |    at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
core_1          |    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
core_1          |    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
core_1          |    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
core_1          |    at System.Linq.Queryable.First[TSource](IQueryable`1 source)
core_1          |    at Faction.Common.Backend.Database.FactionRepository.GetCommandParameter(String CommandName, Int32 Position) in /home/jared/source/faction/Faction.Common/Backend/Database/Respository.cs:line 187
core_1          |    at Faction.Core.Handlers.NewConsoleMessageEventHandler.ProcessCommand(String Command, Int32 AgentId) in /app/Handlers/ConsoleMessageEventHandler.cs:line 344
core_1          |    at Faction.Core.Handlers.NewConsoleMessageEventHandler.Handle(NewConsoleMessage newConsoleMessage, String replyTo, String correlationId) in /app/Handlers/ConsoleMessageEventHandler.cs:line 534
core_1          |    at Faction.Common.Backend.EventBus.RabbitMQ.EventBusRabbitMQ.ProcessEvent(String eventName, String message, String replyTo, String correlationId) in /home/jared/source/faction/Faction.Common/Backend/EventBusRabbitMQ/EventBusRabbitMQ.cs:line 328
core_1          |    at Faction.Common.Backend.EventBus.RabbitMQ.EventBusRabbitMQ.<>c__DisplayClass22_0.<<CreateConsumerChannel>b__0>d.MoveNext() in /home/jared/source/faction/Faction.Common/Backend/EventBusRabbitMQ/EventBusRabbitMQ.cs:line 266
core_1          | --- End of stack trace from previous location where exception was thrown ---
core_1          |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
core_1          | --- End of stack trace from previous location where exception was thrown ---
core_1          |    at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
**To Reproduce**
1. Log into Faction
2. Establish an active Marauder agent
3. Send the following command to the agent: `import stdlib`
4. Core crashes

**Expected behavior**
Core should return a message saying the command is invalid. It should not crash.

**Additional context**
We already have functions written to see if a command is available for the agent (used for `show commands`), we need to do some logic like this:

```
if (command exists) {
  if (command is loaded) {
    send command
  } 
  else {
    send 'you need to load module X to use this command' text
  } 
else {
  send 'invalid command' text
}
```

**Comment by jaredhaight** [comment]
This was fixed a little bit ago
