### ISSUE TITLE
Automatically and Programatically Apply Migrations

### ISSUE THREAD

**Issue by 3lpsy** [FactionC2/Faction#36]
**Is your feature request related to a problem? Please describe.**
When booted, the application should automatically apply Migrations. This feature should be toggleable with an env or config flag.

**Describe the solution you'd like**
Leverage dbContext.Database.Migrate

**Describe alternatives you've considered**
It's possible to do some strange bash scripting to push the dotnet process to the background and call dotnet ef manually.

**Additional context**
The primary error I encounter is this one: 
```
Migrating any necessary schemas...

info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
Entity Framework Core 3.0.0 initialized 'FactionDbContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL' with options: MigrationsAssembly=Faction.Common.Backend.Database
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Faction.Common.Backend.Database, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Faction.Common.Backend.Database, Culture=neutral, PublicKeyToken=null'
at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsAssembly..ctor(ICurrentDbContext currentContext, IDbContextOptions options, IMigrationsIdGenerator idGenerator, IDiagnosticsLogger\1 logger)`
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor\2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)`
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor\2.VisitCallSite(ServiceCallSite callSite, TArgument argument)`
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor\2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)`
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor\2.VisitCallSite(ServiceCallSite callSite, TArgument argument)`
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure\1 databaseFacade)`
at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
at Faction.Core.Program.MigrateSchema(IHost host) in /home/vanguard/Playground/faction2/Core/Program.cs:line 128
at Faction.Core.Program.Main(String[] args) in /home/vanguard/Playground/faction2/Core/Program.cs:line 78
```

**Comment by 3lpsy** [comment]
Update:

I'm able to successfully trigger the Migrate() command if I do the following:

1) Generate the Migrations in Faction.Common, not Core, with the following command:

```
$ dotnet ef migrations add --startup-project ./../Core/ Initial --context Faction.Common.Backend.Database.FactionDbContext
```

2) Run the Core with dotnet run:
```
# inside of Core
dotnet run
```

However, this does not create all the tables. It only creates the __EFMigrationsHistory table.

**Comment by 3lpsy** [comment]
It appears that the initial error may have been due to an incorrect setting in csproj where the Core project was pulling the Faction.Common assemby from nuget, and not locally. This was resolved by commenting out ```
<PackageReference Include="Faction.Common" Version="2019.10.3-beta" />
```  so that the csproj resembled: ```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <LangVersion>8</LangVersion>
    <RootNamespace>Faction.Core</RootNamespace>
    <AssemblyName>Faction.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="3.2.1" />
    
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="3.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="3.0.1" />
    <PackageReference Include="Polly" Version="7.1.1" />
    <PackageReference Include="RabbitMQ" Version="3.6.2" />
    <PackageReference Include="RabbitMQ.Client" Version="5.1.1" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
    
    <Reference Include="Faction.Common">
      <HintPath>../Faction.Common/bin/Debug/netstandard2.1/Faction.Common.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
``` Once this has been remediated, the above error not longer triggered. However, I encountered an additional issue where the proper tables were not being generated when dbContext.Database.Migrate(). The only table that would be created would be __EFMigrationHistory indicating that the project was not finding the Migrations folder. Here are instructions to verify the issue and fix it: ```


# TERMINAL 1
mkdir debugfaction;
cd debugfaction; 
git clone git@github.com:3lpsy/FactionCompose.git Compose
git clone git@github.com:3lpsy/FactionConsole.git Console
git clone git@github.com:3lpsy/FactionAPI.git API
git clone git@github.com:3lpsy/FactionCore.git Core
git clone git@github.com:3lpsy/Faction.Common.git Faction.Common
cd API;
## this has a perm fix for uploads
git checkout jim/dev;
cd ../
cd Faction.Common;
git pull;
git checkout development;
dotnet restore;
dotnet build;
cd ../;


# TERMINAL 2
### spin up the database/api/mq
cd Compose;
docker-compose -f docker-compose.local.yml build
### if necessary, destroy the db and other instances
docker-compose -f docker-compose.local.yml down -v
docker-compose -f docker-compose.local.yml up
### let run in the background, this will be spun up and down throughout this process


# TERMINAL 1
cd Core;
### Change .csproj to pull local Faction.Common;
### Should contain a commented out line: '# '
#### Change netstandard2.0 to netstandard2.1 and uncomment out the section: <Reference Include="Faction.Common"><HintPath>../Faction.Common/bin/Debug/netstandard2.1/Faction.Common.dll</HintPath></Reference>'
dotnet restore;


### set the important environment variables
export POSTGRES_HOST=db
export POSTGRES_DATABASE=faction
export POSTGRES_USERNAME=postgres
export POSTGRES_PASSWORD=changemehunter2
export RABBIT_HOST=mq
export RABBIT_USERNAME=guest
export RABBIT_PASSWORD=changemehunter2
export SYSTEM_USERNAME=jim
export SYSTEM_PASSWORD=jim

### make sure /etc/hosts is set with the correct values per the documentation

### perform the standard migration. this should work.
dotnet ef migrations add Initial
dotnet ef database update
### all should have worked

## Next, we want to trigger the error using programatic migrations


# TERMINAL 2
### destroy the database by hitting ctl+c where docker-compose is running, then run the following in the separate terminal
docker-compose -f docker-compose.local.yml down -v
docker-compose -f docker-compose.local.yml up

# TERMINAL 1
### inside Core, make sure env is set and remove old migrations
rm -rf Migrations;
### pull version of project programmable migrations
### may need to git stash to ignore changes to csproj (assuming fresh project, be careful with stash if doing other things)
git checkout jim/dev;
### recreate migratons
dotnet ef migrations add Initial
### make sure all the environment variables are set and that the database (compose project) is up
dotnet run

### should see:
Migrating any necessary schemas...
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.0.0 initialized 'FactionDbContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL' with options: MigrationsAssembly=Faction.Common, Version=2019.10.3.0, Culture=neutral, PublicKeyToken=null
info: Microsoft.EntityFrameworkCore.Migrations[20405]
      No migrations were applied. The database is already up to date.
### no tables will have been created. fix it by doing the following


# TERMINAL 2
### destroy the database by hitting ctl+c where docker-compose is running, then run the following in the separate terminal
docker-compose -f docker-compose.local.yml down -v
docker-compose -f docker-compose.local.yml up

# TERMINAL 1
### inside Core
### make sure all the environment variables are set and that the database (compose project) is up
### remove old migrations
rm -rf Migrations;
### go to Faction.Common
cd ../Faction.Common;
### generate Migrations there
dotnet ef migrations add --startup-project ./../Core/ Initial --context Faction.Common.Backend.Database.FactionDbContext
### rebuild
dotnet build
### return to Core directory
cd ../Core;
### run the project with programatic migratons
dotnet run

# should see something like: 
Applying migration 'xxxxxx_Initial'.
```

**Comment by 3lpsy** [comment]
In addtion, I discovered it was required to use the following assemblyName:

```
            string assemblyName = typeof(FactionDbContext).Assembly.FullName;
```
