### ISSUE TITLE
Gunicorn server cannot use reload option

### ISSUE THREAD

**Issue by 3lpsy** [FactionC2/Faction#38]
**Describe the bug**
When adding the --reload option to the gunicorn server, the server fails to properly kill the worker. Therefore, no new worker with the updated code is spawned.

** Error Message **
```
2019-10-20 02:33:49 [594073] [INFO] [rabbitmq-consumer:_process_data_events] - Consuming..
2019-10-20 02:33:49 [594073] [INFO] [app.py:CreateApp] - Finished.
.. a change is made to the code and the file is saved
[2019-10-20 02:34:16 -0500] [594073] [INFO] Worker reloading: /home/vanguard/Playground/faction2/API/app.py modified
[2019-10-20 02:34:17 -0500] [594073] [INFO] Worker exiting (pid: 594073)
```

**To Reproduce**
Add the --reload option to the gunicorn command in the Dockerfile. The gunicorn command can be either run on the host or in the container

**Expected behavior**
The gunicorn server reloads the application.

**Desktop (please complete the following information):**
I reproduced the bug in both the docker container (using mounted volumes) as well as on the linux host.

**Additional context**
This is most likely either an upstream issue with socketio/flask, eventlet, and/or gunicorn.However, there may be changes that might be required to get eventlet/gunicorn to properly kill the application.

In addition, if you manually kill the gunicorn worker, gunicorn will refresh the server and spawn a new worker (as it should).

I will work further on investigating this, but wanted to create an issue here to track it as it may requires changes within the project.

**Comment by 3lpsy** [comment]
When a file has been changed on the host, gunicorn will attempt to kill the worker. However, the worker will not be killed and will eventually just timeout. Timing out results in the following message: ```
2019-11-02 03:55:30 [9] [INFO] [app.py:CreateApp] - Finished.
 [2019-11-02 03:56:43 +0000] [9] [INFO] Worker reloading: /app/app.py modified
 [2019-11-02 03:56:43 +0000] [9] [INFO] Worker exiting (pid: 9)
 [2019-11-02 04:01:44 +0000] [7] [CRITICAL] WORKER TIMEOUT (pid:9)
Exception ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
   t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
   self._wait_for_tstate_lock()
 File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
   elif lock.acquire(block, timeout):
  File "/usr/lib/python3.6/site-packages/eventlet/semaphore.py", line 115, in acquire
   hubs.get_hub().switch()
  File "/usr/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 298, in switch
   return self.greenlet.switch()
 File "/usr/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 350, in run
   self.wait(sleep_time)
  File "/usr/lib/python3.6/site-packages/eventlet/hubs/poll.py", line 80, in wait
   presult = self.do_poll(seconds)
   File "/usr/lib/python3.6/site-packages/eventlet/hubs/epolls.py", line 31, in do_poll
    return self.poll.poll(seconds)
  File "/usr/lib/python3.6/site-packages/gunicorn/workers/base.py", line 192, in handle_abort
     sys.exit(1)
 SystemExit: 1
# then the server actually restarts
```

**Comment by 3lpsy** [comment]
So as sort of a hack, the --timeout can be set to something short like three seconds. Then, when reload is enabled, the reload will trigger and (almost) immediately timeout and reboot the server. This will suffice as a work around for my solution. I was unable to identify the underlying cause of the initial error but I'll close this issue.

**Comment by fabriciorissetto** [comment]
Exact same problem here, but with django instead of flask. The worker is not being killed then it times out
